### ISSUE TITLE
Logout zrejme nekoduje query parametry v redirect URL

### ISSUE THREAD

**Issue by vlahoda** [ceskaexpedice/kramerius-web-client#647]
V logu tomcatu K7 jsem narazil na nasledujici stacktrace:

`java.net.URISyntaxException: Illegal character in query at index 178: https://openid.snk.sk/auth/realms/backoffice/protocol/openid-connect/logout?redirect_uri=https://dikda.snk.sk/periodical/uuid:eef3a1e4-234c-4b42-a88c-acfa688390e7?fulltext=Korzo: denník
                at java.base/java.net.URI$Parser.fail(URI.java:2913)
                at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
                at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3172)
                at java.base/java.net.URI$Parser.parse(URI.java:3114)
                at java.base/java.net.URI.<init>(URI.java:600)
                at java.base/java.net.URI.create(URI.java:881)
                at cz.incad.kramerius.rest.apiNew.client.v70.ClientUserResource.logout(ClientUserResource.java:419)`

Ten parametr fulltext=Korzo: denník by zrejme mel byt URL encoded

**Comment by annie-cz** [comment]
Můžeme zavřít @vlahoda ?

**Comment by vlahoda** [comment]
URL vypada OK a v logu uz ty chyby nejsou. Zaviram.
